INSERT INTO cocktender.abv_classification(classification) VALUES(0);
INSERT INTO cocktender.abv_classification(classification) VALUES(1);
INSERT INTO cocktender.abv_classification(classification) VALUES(2);
INSERT INTO cocktender.abv_classification(classification) VALUES(3);
INSERT INTO cocktender.abv_classification(classification) VALUES(4);
INSERT INTO cocktender.abv_classification(classification) VALUES(5);
INSERT INTO cocktender.abv_classification(classification) VALUES(6);
INSERT INTO cocktender.abv_classification(classification) VALUES(7);
INSERT INTO cocktender.abv_classification(classification) VALUES(8);
